### PR TITLE
added a clock to differential class

### PR DESCRIPTION
**Pull request by abejgonzalez**
Should `colins-temp` move to master?

### CODE REVIEW

**Comment by colinschmidt** [comment]
We can probably move it to master. I'll check today.

**Comment by abejgonzalez** [comment]
Also, I did this correctly right the `p` gets the inverted clock right? This seems slightly counterintuitive.

**Comment by abejgonzalez** [comment]
@colinschmidt @jwright6323 This seems to be fine? LGTM?

**Review by jwright6323 — APPROVED** [review]
LGTM

**Pull request merged**
